[keyboard]
name = "eh-rmk-k03"
product_name = "eh-rmk-k03"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
chip = "nrf52840"

[host]
# Enable or disable Vial support (default: true)
vial_enabled = true

# Unlock keys for Vial security (optional)
# Keys must be pressed simultaneously to unlock Vial configuration
unlock_keys = [[0, 0], [0, 1]]  # Keys at (row=0,col=0) and (row=0,col=1)

[layout]
rows = 5
cols = 12
layers = 4
matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5)		 	 (0,6) (0,7) (0,8) (0,9) (0,10) (0,11)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5)		 	 (1,6) (1,7) (1,8) (1,9) (1,10) (1,11)
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5)		 	 (2,6) (2,7) (2,8) (2,9) (2,10) (2,11)
(3,0) (3,1) (3,2) (3,3) (3,4) (3,5) 	     (3,6) (3,7) (3,8) (3,9) (3,10) (3,11)
(4,0) (4,1) (4,2) (4,3) (4,4) (4,5)          (4,6) (4,7) (4,8) (4,9) (4,10) (4,11)
"""
keymap = [
    [
        ["A", "B", "C", "D", "E", "f", "g", "h", "i", "j", "k", "l"],
        ["m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "x", "y"],
        ["z", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ],
    [
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ],
    [
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ],
    [
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ],
]

[ble]
enabled = true

[split]
connection = "ble"

[split.central]
rows = 5
cols = 6
row_offset = 0
col_offset = 0

[split.central.matrix]
row_pins = ["P0_29", "P1_11", "P0_09", "P0_24", "P0_13"]
col_pins = ["P0_03", "P0_28", "P1_13", "P0_02", "P1_10", "P0_10"]
# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
# row2col = true

[[split.peripheral]]
rows = 5
cols = 6
row_offset = 0
col_offset = 6

[split.peripheral.matrix]
row_pins = ["P0_13", "P0_24", "P1_13", "P0_02", "P0_29"]
col_pins = ["P0_09", "P0_10", "P0_28", "P0_03", "P1_10", "P1_11"]
# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
# row2col = true

# [[split.peripheral]]
# rows = 2
# cols = 1
# row_offset = 2
# col_offset = 2
# serial = [{ instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" }]
# row_pins = ["PIN_9", "PIN_11"]
# col_pins = ["PIN_10"]

[rmk]
split_peripherals_num = 1

[storage]
# Enable/disable storage feature (default: true)
enabled = true
clear_storage = true
